name: Sponsorkit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update sponsors
        run: npm i && npm run build
        env:
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORKIT_PATREON_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore: update sponsors"
          add: "*.svg *.png"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
